### PR TITLE
Feature/gwr 95

### PR DESCRIPTION
**Pull request by NickNish09**
image

# Description

- Add promoter CTA to causes page

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Dangerous changes
- [ ] Chore (change that does not effect how the code works, eg: change color)
- [ ] Tests

## How to test

Put here all the things need to test this PR and verify your changes, also list any relevant details for tests (eg: have a wallet)

- Test A

### CODE REVIEW

**Comment by letbueno** [comment]
Captura de Tela 2023-07-25 às 15 02 41

I think the image is not occupying the entire background

**Review by letbueno — APPROVED** [review]

**Comment by thaisribon** [comment]
on hover, should it be black?
Captura de Tela 2023-07-25 às 15 05 09

**Comment by NickNish09** [comment]
> Captura de Tela 2023-07-25 às 15 02 41
> I think the image is not occupying the entire background

fixed

**Comment by NickNish09** [comment]
> on hover, should it be black? Captura de Tela 2023-07-25 às 15 05 09

removed the banner component and the darken effect

**Review by thaisribon — APPROVED** [review]

**Pull request merged**
