### PR TITLE
Feat/prod3 424 and 425

### PR DESCRIPTION
**Pull request by leodhb**
# Description
Download page revision
Captura de Tela 2024-02-01 às 17 25 55

A fancy bottom banner redirecting to download page:
Captura de Tela 2024-02-01 às 17 21 17

Some new events focusing on centralizing downloadCTA events.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Dangerous changes
- [ ] Chore (change that does not effect how the code works, eg: change color)
- [ ] Tests

## How to test

Put here all the things need to test this PR and verify your changes, also list any relevant details for tests (eg: have a wallet)

- Test A

### CODE REVIEW

**Comment by thaisribon** [comment]
I think you could add a margin so the support banner is visible
Captura de Tela 2024-02-02 às 08 54 29

**Comment by leodhb** [comment]
> I think you could add a margin so the support banner is visible Captura de Tela 2024-02-02 às 08 54 29

Fixed :)

**Comment by thaisribon** [comment]
The menu on contribution page is hiding the card
Captura de Tela 2024-02-02 às 09 42 17

**Comment by leodhb** [comment]
> The menu on contribution page is hiding the card Captura de Tela 2024-02-02 às 09 42 17

removed

**Review by thaisribon — APPROVED** [review]

**Pull request merged**
